# Generated by Django 5.2.13 on 2026-04-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerActivityOLAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('total_rental', models.IntegerField(default=0)),
                ('total_payment', models.FloatField(default=0.0)),
                ('recency_days', models.IntegerField(default=0)),
                ('rental_frequency', models.FloatField(default=0.0)),
                ('avg_interval', models.FloatField(default=0.0)),
                ('activity_level', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('kmeans_cluster', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_activity_olap',
            },
        ),
        migrations.CreateModel(
            name='CustomerDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'analytics_customer_dim',
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_file', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('total_customers', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'model_info',
            },
        ),
        migrations.CreateModel(
            name='CustomerActivityFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rental', models.IntegerField(default=0)),
                ('total_payment', models.FloatField(default=0.0)),
                ('recency_days', models.IntegerField(default=0)),
                ('rental_frequency', models.FloatField(default=0.0)),
                ('avg_interval', models.FloatField(default=0.0)),
                ('activity_level', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segmentation.customerdim')),
            ],
            options={
                'db_table': 'analytics_customer_activity_fact',
            },
        ),
    ]
