# Generated by Django 5.2.11 on 2026-04-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customeractivityfact',
            table='segmentation_customer_activity_fact',
        ),
        migrations.AlterModelTable(
            name='customerdim',
            table='segmentation_customer_dim',
        ),
    ]
