# Generated by Django 5.2.13 on 2026-05-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_alter_customeractivityfact_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeractivityfact',
            old_name='activity_level',
            new_name='kmeans_cluster',
        ),
    ]
